/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: IMG1                                                  *
* Dimensions:  64 * 64                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmIMG1;

#if 0


/*********************************************************************
*
*  This palette is included for reference only
*  As it is saved as device dependent bitmap without color info.
*  Please note that this bitmap requires the physical palette to be
*  identical to the palette of the display.
*  If this does not work out, please convert your bitmap into a DIB 
*/
/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsIMG1[] = {
  0x000000, 0xFFFFFF
};

#endif

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalIMG1 = {
  2,  // Number of entries
  0,  // No transparency
  NULL
};

static GUI_CONST_STORAGE unsigned char _acIMG1[] = {
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, _XXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________,
  ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________,
  ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________,
  ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________,
  ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________,
  ________, _____XXX, XXXXXXXX, XXXXXXXX, XX__XXXX, XXXXXXXX, XXXXXX__, ________,
  ________, ____XXXX, XXXXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXXX__, ________,
  ________, ____XXXX, XXXXXXXX, XX______, ________, XXXXXXXX, XXXXXXX_, ________,
  ________, ____XXXX, XXXXXXXX, X_______, ________, _XXXXXXX, XXXXXXX_, ________,
  ________, ___XXXXX, XXXXXXXX, ________, ________, ___XXXXX, XXXXXXX_, ________,
  ________, ___XXXXX, XXXXXXX_, ________, ________, ____XXXX, XXXXXXXX, ________,
  ________, ___XXXXX, XXXXXXX_, ________, ________, _____XXX, XXXXXXXX, ________,
  ________, ___XXXXX, XXXXXX__, ________, ________, ______XX, XXXXXXXX, ________,
  ________, __XXXXXX, XXXXXX__, ________, ________, ______XX, XXXXXXXX, ________,
  ________, __XXXXXX, XXXXX___, ________, ________, ____X_XX, XXXXXXXX, ________,
  ________, __XXXXXX, XXXXX___, ________, ________, _XXXXXXX, XXXXXXXX, X_______,
  ________, ___XXXXX, XXXXXXX_, ________, ______XX, XXXXXXXX, XXXXXXXX, X_______,
  ________, ___XXXXX, XXXXXXXX, XXX_____, ____XXXX, XXXX__XX, XXXXXXXX, ________,
  ________, ___XXXXX, XXXXXXXX, XXXXX___, ____XXXX, X_______, XXXXXXXX, ________,
  ________, __XXXXXX, XX______, XXXXX___, ____XXX_, ________, _XXXXXXX, ________,
  ________, __XXXXXX, X_______, _XXX____, ___XXXXX, ____XX__, __XXXXXX, ________,
  ________, __XXXXXX, ________, XXXXXX__, ___XXXXX, XXXXXXXX, X__XXXXX, ________,
  ________, __XXXXXX, ___XXXXX, XXXXX___, ___XXXXX, XXXXXXXX, X__XXXXX, ________,
  ________, ___XXXX_, _XXXXXXX, XXXXX___, ____XXXX, XXXXXXXX, X___XXXX, ________,
  ________, ___XXXX_, _XXXXXXX, XXXX____, ______XX, XXX_____, ____XXXX, X_______,
  ________, ___XXX__, ___X__XX, XXX_____, ________, ________, ____XXXX, ________,
  ________, ___XXX__, ________, ________, ________, ________, _____XXX, ________,
  ________, ___XXX__, ________, ________, ________, ________, _____XX_, ________,
  ________, ___X_X__, ________, ________, ________, ________, ____XXX_, ________,
  ________, _____X__, ________, ________, ________, ________, ____XXX_, ________,
  ________, ____XX__, ________, ________, ________, ________, ____XXX_, ________,
  ________, _____XX_, ________, ________, ________, ________, ____XX__, ________,
  ________, ______X_, ________, ________, ______X_, ________, ___XXX__, ________,
  ________, ________, ________, _____XX_, __XXX_X_, ________, ___X____, ________,
  ________, ________, ________, ____XXXX, XXXXXXX_, ________, ___X____, ________,
  ________, ________, ________, ____XXXX, XXXXX___, ________, ________, ________,
  ________, ________, ________, ________, XX______, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, _______X, _XXX____, ________, ________, ________,
  ________, ________, ________, _____XXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, __XXXXXX, XXXXXXXX, XX______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, XX______, ________, ________,
  ________, ________, ________, _XX_X___, XXXXX___, ________, ________, ________,
  ________, ________, ________, _X______, XXXX____, ________, ________, ________,
  ________, ________, ________, __X___XX, XXXXX___, _____X__, ________, ________,
  ________, ________, ________, ____XX__, ________, _____X__, ________, ________,
  ________, ________, ________, ________, ________, __XXXX__, ________, ________,
  ________, ________, ________, ________, ________, __XXXX__, ________, ________,
  ________, ________, _______X, X_______, ________, XXXXXX__, ________, ________,
  ________, ________, ________, XX______, _______X, XXXX____, ________, ________,
  ________, ________, ________, XXXXX___, ____XXXX, XXX_____, ________, ________,
  ________, ________, ________, _XXXXXXX, XXXXXXXX, XX______, ________, ________,
  ________, ________, ________, __XXXXXX, XXXXXXXX, ________, ________, ________,
  ________, ________, ________, ____XXXX, XXXXXX__, ________, X_______, ________,
  ________, ________, __XX____, _______X, XXXXX___, ________, _XXXXXX_, ________,
  ________, ________, _XX_____, ________, XXXX____, ________, _XX_XXX_, ________,
  ________, ________, ________, ________, XXX_____, ________, ___XXXX_, ________,
  ________, ________, ________, ________, ________, ________, ____XX__, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmIMG1 = {
  64, // xSize
  64, // ySize
  8, // BytesPerLine
  1, // BitsPerPixel
  _acIMG1,  // Pointer to picture data (indices)
  &_PalIMG1   // Pointer to palette
};

/*************************** End of file ****************************/
